name: Yamdb workflow

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r api_yamdb/requirements.txt 

    - name: Lint with flake8
      run: python -m flake8

    - name: Copy workflow file (required by tests)
      run: cp .github/workflows/yamdb_workflow.yml yamdb_workflow.yml

    - name: Test with Pytest
      run: pytest
